### PR TITLE
Linux workaround using wmctrl

### PR DESCRIPTION
**Pull request by deborasetton**
Discussion: https://github.com/ccampbell/sublime-goto-window/issues/6

### CODE REVIEW

**Comment by Grokzen** [comment]
@deborasetton I have tested this patch and i can confirm that it works on Ubuntu 15.10 with ST3 build 3109. The only thing was that i do not have the required program `wmctrl` installed by default on my system so it would be wise to add a note in the Readme or installation instructions for Linux that it is required for this extension to work.

One limitation that i found is that i can only switch to windows that have a saved project that is open in a window. If i for example just open a bunch of random files in a window, it will still show up in the window switcher, but it will not work to switch to that window when used.

**Comment by deborasetton** [comment]
Hi @Grokzen, thanks for trying this out. I wasn't aware that `wmctrl` isn't installed by default. Will add a note to the README. 

I'm not sure I understand the issue you mentioned. The plugin only lists windows that have at least one folder open, which is the case when:
- You open a random folder (e.g., `subl ~/Desktop`); or
- You open a sublime-project

Windows that contain only individual files don't show up on the select menu. It is possible to modify this behavior, but that would be a different commit, of course :)

**Comment by ccampbell** [comment]
@Grokzen can you explain how you are testing the “open a bunch of random files in a window”. From what I can tell, that doesn't work on Mac OS X either. In fact, on OS X if I just drag a bunch of files into Sublime Text that window doesn't even show up in the go to window command (not returned by the Sublime Text api call for `sublime.windows()`). So that could be a bug in Sublime Text

As for `wmctrl` not being installed by default I am wondering if it is possible to add that as a dependency for this package for linux so that it is installed automatically as part of installing this package. I'd rather people be able to install the Sublime Text package and not have to worry about installing external dependencies. It seems like that might not be the simplest thing tho.

From what I understand in the docs here https://packagecontrol.io/docs/dependencies you have to host the binary in a repo, fork and add it to this file via pull request: https://github.com/wbond/package_control_channel/blob/master/repository/dependencies.json, then add a `dependencies.json` file to the root of this repo to tell it to install that binary on linux.

@deborasetton @Grokzen What do you think?

**Comment by Grokzen** [comment]
Yeah i looked into it some more and i found that there was some cached things or folders that i have added and later removed in a window that did not have a project saved. For some reason this addon still tracked that and found it out. But when i added and removed the folder once again, it disappeared from the dropdown menu so i would not bother with that i guess O.o

**Comment by Grokzen** [comment]
If you can vendorise the dependency then i guess it would be ok. Have a line in the readme works equally as well. I have no strong opinion one way or the other :P

**Comment by ccampbell** [comment]
Yes okay. Probably fine to start with a line in the README. If the binary for `wmctrl` is small tho I wonder if it is possible to include it directly in this package. I'm not familiar with how that works or if it is possible. I don't want to over complicate it though. This is still a step in the right direction since it doesn't work now at all :smile:

**Comment by Grokzen** [comment]
The correct solution in the end would still be that ST3 provides a working way to switch between windows across all platforms and that this extension builds ontop of that.

**Comment by ccampbell** [comment]
@Grokzen totally agree! @deborasetton let me know after you have added the `wmctrl` install instructions to the README and I will merge

**Comment by deborasetton** [comment]
Ok! I'll try to look into how Package Control handles dependencies from the links you provided, and see what comes up. I agree that having an external dependency is not ideal.

I'll get back to you.

**Comment by ccampbell** [comment]
@deborasetton Sounds good! Don't spend _too_ much time on it :smile:  Also `wmctrl` might be installed by default on some linux distributions.

As @Grokzen pointed out, this is only an issue due to a bug in Sublime Text itself so after the bug is fixed, the workaround shouldn't be needed. 

I am fine with adding a line in the README saying that linux users need to `sudo apt-get install wmctrl` (or whatever command is needed).

**Comment by deborasetton** [comment]
I ended up just updating the README and adding an `except` clause to display an error message to the user in case the call to `wmctrl` fails. This way, the plugin won't fail silently in case of an error, and the user won't be lost as to why nothing happened. What do you think?

**Comment by ccampbell** [comment]
Looks good to me! Thanks

**Pull request merged**
